baseURL = 'https://wiki.skelmis.co.nz/'
languageCode = 'en-GB'
title = 'My Personal Wiki'
theme = "hugo-geekdoc"


pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true


# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode or when nesting shortcodes (e.g. img within
    # columns or tabs)
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[params]
  geekdocRepo = "https://github.com/skelmis/wiki"
  geekdocNextPrev = true
  geekdocEditPath = "blob/master"
  geekdocPageLastmod = true
  geekdocToC = 3
  geekdocPrivacyPolicy = "#"
  geekdocTagsToMenu = true




